### ISSUE TITLE
tagsedit: the implementation is broken: tags from "Objects for merge" left out!

### ISSUE THREAD

**Issue by qknight** [kartevonmorgen/FairSync#43]
the tagsedit does not work correctly.

## Problem
No tags get loaded from csv
tags: SDG16,gwn, PEACE,frieden,CONTINENT,ASSOCIATION,non-profit,Verein
![grafik](https://github.com/user-attachments/assets/c3ed9234-6167-4dab-a72e-f7f58751bfa6)

---
Initial Bug-Report: https://github.com/kartevonmorgen/FairSync/issues/41

**Comment by qknight** [comment]
fixed in fba4d0fe6310874ef30fd8215077d7009d8056c7

**Comment by wellemut** [comment]
@qknight on https://fairsync.de/# its still not working:

the Tags from the "objects for merege" still don't appear
![grafik](https://github.com/user-attachments/assets/65db8b12-eb16-47ff-838f-775ee71f136f)

If I choose the csv file as destination, only the csv-file tags are used and the ones of the existing entry is dropped:
![grafik](https://github.com/user-attachments/assets/7dd02100-c9fa-4ee8-ae79-13edaa975a55)

Test Entries: 
[2GWN20.csv](https://github.com/user-attachments/files/18256398/2GWN20.csv)

**Comment by wellemut** [comment]
Jetzt geht es bei mir auch. Alle Stichworte, auch vom "Objects for merge" werden angezeigt:
![Image](https://github.com/user-attachments/assets/c43f1829-cb04-4fcb-82df-5236bf98f327)

aber sie kommen noch nicht in der Karte an. Dazu ein neues Issue: https://github.com/kartevonmorgen/FairSync/issues/45
